### ISSUE TITLE
admin for users

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#15]
It feels like important functionality is lost by only having the ability to edit user _roles_ in User Admin. What about being able to edit other user fields like the normal MEAN.JS does?

Wouldn't you want that functionality, especially under this scenario, which must be more common than the social provider scenario/any random person can sign-up scenario: 
- A random user is not allowed to sign-up
- No social providers
- Only a user with User Admin rights would create a new user either manually or via upload of a spreadsheet with pre-defined fields like first name, last name, email address
- The User Admin person would have to assign the appropriate role(s) to the new user(s)
- Once the User Admin person creates a new user with role(s), the new user would receive a registration email with a link that opens to a registration page where the user creates a password
- Upon creating a password, the new user can access the system

**Comment by francisdaigle** [comment]
Absolutely. At the time of PEAN's creation, I was just wanting to get something "out the door", so to speak. That meant focusing on the core functionality. 

Most of our applications utilize "single page" admin panels w/ modals rather than MEAN's "multi-page" approach. Hence why a simple, one-page user admin was chosen.    

We'll be starting a new project using PEAN quite soon. Perhaps we'll try to make a further contribution to a more substantial user admin at this time.
